#!/usr/bin/python3

def raise_exception_msg(message=""):
    '''raise a NameError with message'''
    raise NameError(message)
